// WPF と WinForms の名前空間衝突を解消するグローバルエイリアス
global using Application = System.Windows.Application;
global using Binding = System.Windows.Data.Binding;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Color = System.Windows.Media.Color;
global using MessageBox = System.Windows.MessageBox;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Orientation = System.Windows.Controls.Orientation;
global using UserControl = System.Windows.Controls.UserControl;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using MenuItem = System.Windows.Controls.MenuItem;
